spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssacation?serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  #jpa
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        show_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 9999

# mybatis
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.ssacation.model.dto


# logging
logging:
  level:
    com.ssacation: debug



