spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SSACATION?serverTimezone=UTC
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

  #jpa
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
        show_sql: true


server:
  port: 9999

# mybatis
mybatis:
  mapper-locations: mappers/**/*.xml
  type-aliases-package: com.SSACATION.model.dto


# logging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace # 쿼리의 ?에 어떤 값이 들어가는지 TRACE Log에 값을 보여주는 설정



